# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tom Dalby
tagline:          ' '
description:      'A sporadic dev blog.'
url:              http://thomasjackdalby.github.io
baseurl:          /

author:
  name:           'Tom Dalby'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
